// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface IMicrosoftDeviceAuth { device_code: string, expires_in: number, interval: number, message: string, user_code: string, verification_uri: string, }