// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IEventLoadingBarType = { type: "java_download", version: number, } | { type: "process_children", id: string, server_id: string, };