// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IEventLoadingBarType } from "./IEventLoadingBarType";

export interface IEventLoadingPayload { event: IEventLoadingBarType, loader_uuid: string, fraction: number, message: string, }