// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ILASCModpackActionActionPlayer } from "./ILASCModpackActionActionPlayer";
import type { ILASCModpackActionActionRule } from "./ILASCModpackActionActionRule";

export interface ILASChildrenModpackAction { rule: ILASCModpackActionActionRule, players: Array<ILASCModpackActionActionPlayer>, }