// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ILASChildrenModpackAction } from "./ILASChildrenModpackAction";
import type { ILauncherAssetsServerChildrenAssets } from "./ILauncherAssetsServerChildrenAssets";

export interface ILauncherAssetsServerChildren { id: string, ip: string, name: string, image_url: string, minecraft_type: string, minecraft_version: string, action: ILASChildrenModpackAction, assets: ILauncherAssetsServerChildrenAssets, }