// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ILauncherAssetsServer } from "./ILauncherAssetsServer";

export interface ILauncherAssets { date: string, servers: Array<ILauncherAssetsServer>, }