// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ILauncherAssetsServerChildren } from "./ILauncherAssetsServerChildren";

export interface ILauncherAssetsServer { id: string, name: string, imageUrl: string, description: string, officialWebLinkUrl: string, children: Array<ILauncherAssetsServerChildren>, }