// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ILauncherAssetsServerChildren } from "./ILauncherAssetsServerChildren";
import type { ILauncherAssetsServerChildrenAnnounment } from "./ILauncherAssetsServerChildrenAnnounment";

export interface ILauncherAssetsServer { id: string, name: string, image_url: string, description: string, official_web_link_url: string, children: Array<ILauncherAssetsServerChildren>, announment: Array<ILauncherAssetsServerChildrenAnnounment>, }