// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ILASChildrenModpackAction } from "./ILASChildrenModpackAction";
import type { ILAServerChildrenModpack } from "./ILAServerChildrenModpack";

export interface ILauncherAssetsServerChildren { id: string, ip: string, name: string, imageUrl: string, minecraftType: string, minecraftVersion: string, action: ILASChildrenModpackAction, modpack: ILAServerChildrenModpack, }