// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IStoreProfilesMicrosoftAuth } from "./IStoreProfilesMicrosoftAuth";
import type { IStoreProfilesPlayer } from "./IStoreProfilesPlayer";
import type { IStoreProfilesUser } from "./IStoreProfilesUser";

export interface IStoreProfiles { microsoft_auth: IStoreProfilesMicrosoftAuth, user: IStoreProfilesUser, player: IStoreProfilesPlayer, }