// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface IStoreSettingSelectedServer { main_id: string, child_server_id: string, }